name: AI Shorts Generator

on:
  workflow_dispatch:

jobs:
  build-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Test FFmpeg
        run: ffmpeg -version